//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyTicketTask.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public int Airplane_Id { get; set; }
        public int Schedules_Id { get; set; }
        public int City_Id { get; set; }
        public int FlightType_Id { get; set; }
    
        public virtual Airplane Airplane { get; set; }
        public virtual City City { get; set; }
        public virtual FlightType FlightType { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
